# fly.toml app configuration file generated for banze-billy-django-cv on 2025-07-16T21:09:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file for banze-billy-django-cv

app = 'banze-billy-django-cv'
primary_region = 'jnb'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'

# ✅ Only one volume mount is allowed
[[mounts]]
  source = "data"
  destination = "/data"
