# Generated by Django 5.2.2 on 2025-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.TextField(),
        ),
    ]
