# Generated by Django 5.2.2 on 2025-06-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='project_link',
            field=models.URLField(blank=True, help_text='Add the URL to your project (e.g., GitHub, live site)', max_length=500, null=True),
        ),
    ]
