# Generated by Django 5.2.2 on 2025-06-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
